services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: roomvisa 
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d roomvisa"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:1234

volumes:
  pgdata:
